### ISSUE TITLE
Поддержка Eloquent 

### ISSUE THREAD

**Issue by helloimsergio** [glushkovds/phpclickhouse-laravel#10]
Когда планируете добавить модели?

**Comment by glushkovds** [comment]
Здравствуте!
Модели были изначально
```
<?php


namespace App\Models\Clickhouse;

use PhpClickHouseLaravel\BaseModel;

class MyTable extends BaseModel
{
    // Not necessary. Can be obtained from class name MyTable => my_table
    protected $table = 'my_table';

}
```
Или Вы про что то другое?

**Comment by helloimsergio** [comment]
Имею в виду, чтобы они наследовали lluminate\Database\Eloquent\Model

**Comment by glushkovds** [comment]
@helloimsergio я делал попытку наследования от eloquent, но натолкнулся на то,что слишком много нужно реализовывать методов, часть из которых в принципе не реализуема из за особенностей самой БД.

Так что ответ - от реализации я пока что не отказываюсь, но и сроков указать не могу.

Для чего Вам Eloquent? Какой либо конкретный функционал можно добавить в текущую реализацию.

**Comment by baltun** [comment]
Как вариант ответа на вопрос из предыдущего сообщения:
возможно ли сделать, чтобы модель пакета можно было использовать в качестве ресурса для Laravel Nova, так, чтобы хотя-бы в минимальном функционале, без дополнительных настроек (или с какими-то заданными настройками, например только на просмотр с пэйджингом), модель начала бы отображаться в UI Новы?

**Comment by glushkovds** [comment]
> 

Laravel Nova я не использую, поэтому с моей стороны продвижений в этом направлении пока не запланировано.  
Вы всегда можете предложить свою реализацию на обсуждение.
