### ISSUE TITLE
Несогласованность типов при вызове smi2/phpclickhouse

### ISSUE THREAD

**Issue by baltun** [glushkovds/phpclickhouse-laravel#12]
local.ERROR: Argument 1 passed to ClickHouseDB\Client::setTimeout() must be of the type int, string given, called in /var/www/vendor/glushkovds/phpclickhouse-laravel/src/Connection.php on line 32 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to ClickHouseDB\\Client::setTimeout() must be of the type int, string given, called in /var/www/vendor/glushkovds/phpclickhouse-laravel/src/Connection.php on line 32 at /var/www/vendor/smi2/phpclickhouse/src/Client.php:186)

помогает явное указание типов, но не хотелось бы менять код библиотеки:
    $conn->client->setTimeout((int)$config['timeout_query']);
    $conn->client->setConnectTimeOut((int)$config['timeout_connect']);

**Comment by glushkovds** [comment]
@baltun благодарю!

Поправил в v1.14.2

Недостаточно внимательно проверил последний PR от участника проекта.

Пора уже тестами покрыть код, займусь в ближайшее время.
