### ISSUE TITLE
update  requirements pls

### ISSUE THREAD

**Issue by lexxkn** [glushkovds/phpclickhouse-laravel#2]
glushkovds/phpclickhouse-laravel[v1.5.0, ..., v1.5.2] require the-tinderbox/clickhouse-builder ^3.0 -> found the-tinderbox/clickhouse-builder[3.0.0, 3.0.1, 3.1.0] but it conflicts with your root composer.json require (^4.0).

**Comment by glushkovds** [comment]
Hi!

I will check and fix asap.
Also feel free to open pull request with fix.

**Comment by glushkovds** [comment]
I released v1.5.4 with fix of major version of the-tinderbox/clickhouse-builder.
Please, do your composer update.
