### ISSUE TITLE
Error in obtaining the total number of records

### ISSUE THREAD

**Issue by liaozongchao** [glushkovds/phpclickhouse-laravel#25]
dev.ERROR: Call to undefined method PhpClickHouseLaravel\Builder::count() {"exception":"[object] (Error(code: 0): Call to undefined method PhpClickHouseLaravel\\Builder::count()

**Comment by glushkovds** [comment]
Hi!

Please use `$query->getCountQuery()->get()->fetchRow('count')` instead.

**Comment by liaozongchao** [comment]
thank you ,I used:   $query->getCountQuery()->getRows()[0]["count"]
