### ISSUE TITLE
Call to undefined method PhpClickHouseLaravel\Builder::newQuery()

### ISSUE THREAD

**Issue by mosothonLijian** [glushkovds/phpclickhouse-laravel#26]
`$query->where(function ($q){
                $q->orWhere('member_id', 123123131);
            });`

Error:
`Call to undefined method PhpClickHouseLaravel\Builder::newQuery()`

**Comment by opiy-org** [comment]
Did you make step 3 from readme ?

3. Add service provider into your config/app.php file providers section:
\PhpClickHouseLaravel\ClickhouseServiceProvider::class,`

**Comment by glushkovds** [comment]
fixed in https://github.com/glushkovds/phpclickhouse-laravel/releases/tag/v1.18.1
