### ISSUE TITLE
Undefined constant "ClickHouseDB\Transport\CURLOPT_SSL_VERIFYHOST"

### ISSUE THREAD

**Issue by get-route** [glushkovds/phpclickhouse-laravel#32]
Приветствую! Не могли бы подсказать в чем тут дело. Поставил пакет, миграция прошла успешно. Однако после попытки выбрать данные из БД или вставить их, идет следующее сообщение - Undefined constant "ClickHouseDB\Transport\CURLOPT_SSL_VERIFYHOST"
В чем причина?

**Comment by glushkovds** [comment]
Добрый день! Похоже, что у вас не установлен curl
