### ISSUE TITLE
Ошибка Call to a member function prepare() on null

### ISSUE THREAD

**Issue by Arnon-hs** [glushkovds/phpclickhouse-laravel#4]
Доброго времени суток, столкнулся с ошибкой при использовании вашей библиотеки(1).
![image](https://user-images.githubusercontent.com/49660318/112761545-7741c500-9004-11eb-883f-6afdffaef0bd.png)
Изначально я пытался создать миграции по вашей документации но у меня была другая ошибка(2):
![image](https://user-images.githubusercontent.com/49660318/112761582-a0faec00-9004-11eb-8459-3a7c5199a9b4.png)
Я создал таблицы вручную и при попытке записать в базу у меня появляется ошибка (1). 

Помогите решить проблему, пожалуйста!

**Comment by glushkovds** [comment]
Здравствуйте! По скриншотам видно только то, что проблема у Вас в laravel http middleware и в laravel database schema builder.

**Comment by glushkovds** [comment]
Если у Вас осталась проблема, опишите ее подробнее. Пока закрываю тикет
