### ISSUE TITLE
Поддержка PHP 8

### ISSUE THREAD

**Issue by asvechkar** [glushkovds/phpclickhouse-laravel#5]
Добрый день. Планируете сделать поддержку PHP 8?

**Comment by glushkovds** [comment]
Здравствуйте! Пока в ближайших планах нет, т.к. мы пока что используем PHP 7.4.
Вы можете предложить свой PR, я обязательно его рассмотрю.

**Comment by glushkovds** [comment]
https://github.com/glushkovds/phpclickhouse-laravel/pull/11
