### ISSUE TITLE
Failed migration

### ISSUE THREAD

**Issue by 2618094** [glushkovds/phpclickhouse-laravel#6]
Hello!
When I try to migrate - error appears.
If I delete code about transactions (only call $callback()) in Migrator.php - migration successful.
Laravel v8.48.1

```
  Call to a member function supportsSchemaTransactions() on null

  at vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:398
    394▕ 
    395▕                 $this->fireMigrationEvent(new MigrationEnded($migration, $method));
    396▕             }
    397▕         };
  ➜ 398▕         $this->getSchemaGrammar($connection)->supportsSchemaTransactions()
    399▕             && $migration->withinTransaction
    400▕                     ? $connection->transaction($callback)
    401▕                     : $callback();
    402▕     }
```

**Comment by glushkovds** [comment]
Hello! Please show your migration. It must extend \PhpClickHouseLaravel\Migration

For example:

```php
class ClickhouseCreateSomeTable extends \PhpClickHouseLaravel\Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        static::write("
            CREATE TABLE some_table (
                created_at DateTime DEFAULT now(),
                data String
            )
            ENGINE = MergeTree()
            ORDER BY (created_at)
        ");
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        static::write('DROP TABLE some_table');
    }
}
```

**Comment by 2618094** [comment]
Yep

`<?php

use PhpClickHouseLaravel\Migration;

class CreateEventsTable extends Migration
{
    protected $connection = 'clickhouse';
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        static::write('
            CREATE TABLE events (
                event_time DateTime,
                event_date Date   default toDate(event_time),
                event_type String default \'\',
                project_id Int64  default CAST(10000, \'Int64\'),
                client_id  String default \'\',
                user_id    Int64  default CAST(0, \'Int64\'),
                ip         IPv4,
                params     String default \'\'
            )
            ENGINE = MergeTree()
            ORDER BY (event_time)
        ');
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        static::write('DROP TABLE events');
    }
}
`

**Comment by glushkovds** [comment]
OK, thanks. I will see a little later.

However feel free to suggest your own PR.

**Comment by glushkovds** [comment]
@2618094 please check out my fix: https://github.com/glushkovds/phpclickhouse-laravel/tree/v1.11.0
