### ISSUE TITLE
Failed migration

### ISSUE THREAD

**Issue by milinsky** [glushkovds/phpclickhouse-laravel#8]
```
<?php

use PhpClickHouseLaravel\Migration;

class CreateWeatherProvidersStatisticsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        static::write('
            CREATE TABLE weather_providers_statistics (
                id UInt32,
                created_at DateTime,
                provider_name String
            )
            ENGINE = MergeTree()
            ORDER BY (id)
        ');
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        static::write('DROP TABLE weather_providers_statistics');
    }
}
```

`php artisan migrate`

Error:
```
In Builder.php line 136:
                                                          
  Call to a member function compileTableExists() on null
```

**Comment by eloscuro** [comment]
I have the same problem.
BTW it was mentioned in [this issue](https://github.com/glushkovds/phpclickhouse-laravel/issues/6) and [this closed issue](https://github.com/glushkovds/phpclickhouse-laravel/issues/4).

Looks like we need to implement class which extends \Illuminate\Database\Schema\Grammars\Grammar class.
Similar to \Illuminate\Database\Schema\Grammars\MySqlGrammar, but for ClickHouse.

**Comment by glushkovds** [comment]
@eloscuro yes, you are right. I use main DB (Postgresql) for all migrations (and for ClickHouse including) in my projects.

Now I don't have enough time to implement missing code for using migrations and ClickHouse as standalone database.

I can do it later. Also you can help me 😉

**Comment by BirdyUK** [comment]
@glushkovds - Have you experienced  "Call to undefined method Tinderbox\Clickhouse\Client::select()"?

Query im running is:  

```
        $q = TestModel::select(['id'])->where('id', '=', 'bcb53d00-3f61-d26d-9acf-442bd516d73c')->get();
```

Thanks

**Comment by glushkovds** [comment]
@BirdyUK Hi! Your `TestModel` must extends `\PhpClickHouseLaravel\BaseModel`

**Comment by glushkovds** [comment]
@milinsky please check out my fix: https://github.com/glushkovds/phpclickhouse-laravel/tree/v1.11.0
